site_name: Documentazione BPM
site_url: https://BPM.docs
theme:
  name: material
  logo: assets/favicon-96x96.png
  favicon: assets/fav.ico
  palette:
      primary: custom
      accent: custom
  language: it
extra:
  alternate:
    - name: Italiano
      link: /it/
      lang: it
    - name: English
      link: /en/
      lang: en
extra_css:
  - stylesheets/shape.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
