site_name: Documentazione BPM
site_url: https://centrosoftware-dev.github.io/bpm-docs/
plugins:
    - search
    - awesome-pages
theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.suggest
    - search.share
  name: material
  logo: assets/favicon-96x96.png
  favicon: assets/fav.ico
  icon:
    annotation: material/arrow-right-circle 
  palette:
    primary: custom
    accent: custom
  language: it
extra:
  alternate:
    - name: Italiano
      link: /
      lang: it
    - name: English
      link: /bpm-docs/en/
      lang: en
extra_css:
  - stylesheets/shape.css

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
