nav:
  - index.md
  - Opzioni generali: opzioni-generali
  - Opzioni modelli: opzioni-modelli
  - Utenti e gruppi: utenti-e-gruppi
  - Contatti: contatti
  - Dashboard: dashboard
  - Report: report
  - Allegati: allegati
  - Tabelle: tabelle
  - Connettori: connettori
  - Altre opzioni: altre-opzioni
