nav:
  - Inizia:
      - Home: index.md
      - Tutorial: tutorial/index.md
      - Corso base: tutorial/corso-base
      - Corso avanzato: tutorial/corso-avanzato
  - Processi: modelli-di-processo
  - Documenti: classi-documentali
  - Integrazione: integrazione
  - Intelligenza artificiale: intelligenza-artificiale
  - Amministrazione: amministrazione
  - Parti comuni: parti-comuni
