nav:
  - Home: index.md
  - Tutorial: tutorial
  - Modelli di processo: modelli-di-processo
  - Classi documentali: classi-documentali
  - Strumenti condivisi: strumenti-condivisi
  - Menu Configurazione: menu-configurazione
  - Sistema: sistema
